SUBDIRS := src{% if python_binding %} python{% endif %}

all: clib_install $(SUBDIRS)
$(SUBDIRS):
	$(MAKE) -C $@

clib_install:
	clib install .

rules:
	$(MAKE) -C src scanner.re {{ prefix | trim('_') }}_scanner.c

deploy:
	bumpversion patch
	git push
	git push --tags

.PHONY: all $(SUBDIRS)

