word_{{name}}/token_types.py:
	{% if standard_token_types %}clib install ../clib.json -o ../deps{% endif %}.
	./gen_token_types.sh {% if standard_token_types %}../deps/token_types/token_types.h{% else %}../src/token_types/token_types.h{% endif %} > word_{{name}}/token_types.py
